name: Build and test Go
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.18.0"
      - name: Build
        env:
          GOPROXY: "https://proxy.golang.org"
        run: go build -tags=nomsgpack .
